// GENERATED BY tools/icons/build_owm_icon_font.py. DO NOT EDIT.
//
// Glyphs Material Icons does not have: game species, animal sign, and
// the terrain and access features the outdoors needs. Drawn from
// artwork by Caro Asercion, Cathelineau, Delapouite, Lorc, https://game-icons.net,
// licensed CC BY 3.0. See tools/icons/svg/ATTRIBUTION.md.

import 'package:flutter/widgets.dart';

/// The codepoints in this app's own icon font.
///
/// Each is also the codepoint the map's SDF sprite was rasterised from,
/// and a test asserts the two have not drifted apart.
abstract final class OwmIcons {
  static const IconData deer = IconData(0xE000, fontFamily: 'OwmIcons');
  static const IconData bear = IconData(0xE001, fontFamily: 'OwmIcons');
  static const IconData boar = IconData(0xE002, fontFamily: 'OwmIcons');
  static const IconData rabbit = IconData(0xE003, fontFamily: 'OwmIcons');
  static const IconData squirrel = IconData(0xE004, fontFamily: 'OwmIcons');
  static const IconData beaver = IconData(0xE005, fontFamily: 'OwmIcons');
  static const IconData waterfowl = IconData(0xE006, fontFamily: 'OwmIcons');
  static const IconData feather = IconData(0xE007, fontFamily: 'OwmIcons');
  static const IconData wolf = IconData(0xE008, fontFamily: 'OwmIcons');
  static const IconData tracks = IconData(0xE009, fontFamily: 'OwmIcons');
  static const IconData forest = IconData(0xE00A, fontFamily: 'OwmIcons');
  static const IconData swamp = IconData(0xE00B, fontFamily: 'OwmIcons');
  static const IconData waterfall = IconData(0xE00C, fontFamily: 'OwmIcons');
  static const IconData cave = IconData(0xE00D, fontFamily: 'OwmIcons');
  static const IconData spring = IconData(0xE00E, fontFamily: 'OwmIcons');
  static const IconData mushroom = IconData(0xE00F, fontFamily: 'OwmIcons');
  static const IconData berries = IconData(0xE010, fontFamily: 'OwmIcons');
  static const IconData nuts = IconData(0xE011, fontFamily: 'OwmIcons');
  static const IconData towerStand = IconData(0xE012, fontFamily: 'OwmIcons');
  static const IconData glassing = IconData(0xE013, fontFamily: 'OwmIcons');
  static const IconData gate = IconData(0xE014, fontFamily: 'OwmIcons');
  static const IconData farm = IconData(0xE015, fontFamily: 'OwmIcons');
  static const IconData bridge = IconData(0xE016, fontFamily: 'OwmIcons');
  static const IconData atvTrail = IconData(0xE017, fontFamily: 'OwmIcons');
  static const IconData fish = IconData(0xE018, fontFamily: 'OwmIcons');
  static const IconData firepit = IconData(0xE019, fontFamily: 'OwmIcons');
  static const IconData stand = IconData(0xE01A, fontFamily: 'OwmIcons');
  static const IconData harvest = IconData(0xE01B, fontFamily: 'OwmIcons');
}

/// Credit for the artwork the glyphs above were drawn from.
///
/// CC BY 3.0 asks for attribution in the work itself, not just in a
/// repository, so the Settings screen shows this. Generated from the
/// same table as the font so that adding artwork by someone new cannot
/// leave them uncredited.
abstract final class OwmIconsCredit {
  static const String source = 'https://game-icons.net';
  static const String licence = 'CC BY 3.0';
  static const String licenceUrl = 'https://creativecommons.org/licenses/by/3.0/';
  static const List<String> authors = <String>[
    'Caro Asercion',
    'Cathelineau',
    'Delapouite',
    'Lorc',
  ];

  /// Worded the way the upstream licence asks for it.
  static const String line = 'Icons made by Caro Asercion, Cathelineau, Delapouite and Lorc, available at https://game-icons.net';
}
